### ISSUE TITLE
It is not clear from the README whether azul supports Rust & C, Rust & C++ or Rust & C & C++

### ISSUE THREAD

**Issue by vn971** [fschutt/azul#303]
In the description of the project, it says "for Rust and C++":
![2022 02 14_10:59:52ee](https://user-images.githubusercontent.com/1547617/153845886-d67cd092-9508-433a-adfc-7e47872057b4.png)

Below in the About section, it says "Rust and C":

> Azul is a library for creating graphical user interfaces in Rust and C. It mixes paradigms from func...

In sections below you can see examples for all of C, C++ and Rust. Github tags also show all 3 languages.

I heavily suspect that all 3 languages are supported, but if that's indeed true, it'd be nice to update the README to say so. I can send a PR once confirmed of course

**Comment by fschutt** [comment]
> I heavily suspect that all 3 languages are supported

It is true (at least in theory), since the bindings are auto-generated from a [JSON description](https://raw.githubusercontent.com/fschutt/azul/master/api.json) (python bindings [done via PyO3](https://raw.githubusercontent.com/fschutt/azul/master/azul-dll/src/python.rs), C++ via [`azul.hpp`](https://raw.githubusercontent.com/fschutt/azul/master/api/cpp/azul.hpp) and C via [`azul.h`](https://raw.githubusercontent.com/fschutt/azul/master/api/c/azul.h)). 

However, I admit that the bindings are currently broken, but both C and Python used to work in the 0.1-alpha release.

I am not sure whether I am over-promising anything. Right now I try to finish the Rust bindings first, then C, then Python and C++ at last.

**Comment by vn971** [comment]
@fschutt Thanks for the response! Makes sense. Would the README benefit from more alignment?

Based on what I read in this message, I would humbly propose writing something like "Rust, C and C++" in the top section, since this is the aim and the project is still alpha. Below I would explain

I just wanted to make more clarity for me and for new people, no pressure :) I'll see if I can maybe devise a small PR to be merged or rejected. Also, thanks again for explaining!
